# Common settings
# ===============
# MySQL
mysql: &mysql
  adapter:  mysql2
  encoding: utf8
  host:     localhost

# Environments
# ============

development:
  <<: *mysql
  database: lifecycle-dashboard_development
  username: root
  password:

test:
  <<: *mysql
  database: lifecycle-dashboard_test
  username: root
  password:

production:
  <<: *mysql
  database: lifecycle-dashboard_production
  username: root
  password:
